esphome:
  name: pflanzenlicht
  platform: ESP8266
  board: esp01_1m
wifi:
  ssid: "Labor 2.0"
  password: "nerdhoehle2"
  fast_connect: true
web_server:
  port: 80
logger:
ota:
  password: 'olaota!1'

binary_sensor:
  - platform: status
    name: "pflanzenlichtStatus"
  - platform: gpio
    pin: 
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "pflanzenlichtS1"
    on_press:
      then:
        - switch.toggle: r1
  - platform: gpio
    pin: 
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "pflanzenlichtS2"
    on_press:
      then:
        - switch.toggle: r2
  - platform: gpio
    pin: 
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    name: "pflanzenlichtS3"
    on_press:
      then:
        - switch.toggle: r3
  - platform: gpio
    pin: 
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "pflanzenlichtS4"
    on_press:
      then:
        - switch.toggle: r4
switch:
  - platform: gpio
    name: "pflanzenlichtR1"
    id: r1
    pin: GPIO12
  - platform: gpio
    name: "pflanzenlichtR2"
    pin: GPIO5
    id: r2
  - platform: gpio
    name: "pflanzenlichtR3"
    pin: GPIO4
    id: r3
  - platform: gpio
    name: "pflanzenlichtR4"
    pin: GPIO16
    id: r4
status_led:
  pin:
    number:  GPIO13
    inverted: True
api:
  password: olagr0wth!1
