esphome:
  name: plug5
  platform: ESP8266
  board: esp01_1m
  

wifi:
  ssid: "Labor 2.0"
  password: "nerdhoehle2"
  fast_connect: true

logger:

web_server:
  port: 80

#prometheus:

ota:
  password: "olaota!1"
api:
  password: "olagr0wth!1"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: True
    name: "plug5_button"
    on_press:
      - switch.toggle: relay

light:
  - platform: rgb
    name: "plug5_rgb"
    red: led1
    blue: led2
    green: led3

output:
  - platform: esp8266_pwm
    id: led1
    pin: GPIO00
  - platform: esp8266_pwm
    id: led2
    pin: GPIO02
  - platform: esp8266_pwm
    id: led3
    pin: GPIO04

switch:
  - platform: gpio
    name: "plug5_relay"
    pin: GPIO15
    id: relay

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current_resistor: 0.00221
    voltage_divider: 871
    current:
      name: "plug5_current"
      unit_of_measurement: A
    voltage:
      name: "plug5_voltage"
      unit_of_measurement: V
    power:
      name: "plug5_wattage"
      unit_of_measurement: W
    change_mode_every: 8
    update_interval: 1s
